using System.Collections.Generic;

namespace GuitarNoteTeacher.Core.Services.NotesService.Objects
{
    public static class Notes
    {
        public static Dictionary<string, string> fretNotes = new Dictionary<string, string>()
        {
            { "E0","E" },
            { "E1","F" },
            { "E2","F#" },
            { "E3","G" },
            { "E4","G#" },
            { "E5","A" },
            { "E6","A#" },
            { "E7","B" },
            { "E8","C" },
            { "E9","C#" },
            { "E10","D" },
            { "E11","D#" },
            { "E12","E" },

            { "A0","A" },
            { "A1","A#" },
            { "A2","B" },
            { "A3","C" },
            { "A4","C#" },
            { "A5","D" },
            { "A6","D#" },
            { "A7","E" },
            { "A8","F" },
            { "A9","F#" },
            { "A10","G" },
            { "A11","G#" },
            { "A12","A" },

            { "D0","D" },
            { "D1","D#" },
            { "D2","E" },
            { "D3","F" },
            { "D4","F#" },
            { "D5","G" },
            { "D6","G#" },
            { "D7","A" },
            { "D8","A#" },
            { "D9","B" },
            { "D10","C" },
            { "D11","C#" },
            { "D12","D" },

            { "G0","G" },
            { "G1","G#" },
            { "G2","A" },
            { "G3","A#" },
            { "G4","B" },
            { "G5","C" },
            { "G6","C#" },
            { "G7","D" },
            { "G8","D#" },
            { "G9","E" },
            { "G10","F" },
            { "G11","F#" },
            { "G12","G" },

            { "B0","B" },
            { "B1","C" },
            { "B2","C#" },
            { "B3","D" },
            { "B4","D#" },
            { "B5","E" },
            { "B6","F" },
            { "B7","F#" },
            { "B8","G" },
            { "B9","G#" },
            { "B10","A" },
            { "B11","A#" },
            { "B12","B" },

            { "e0","E" },
            { "e1","F" },
            { "e2","F#" },
            { "e3","G" },
            { "e4","G#" },
            { "e5","A" },
            { "e6","A#" },
            { "e7","B" },
            { "e8","C" },
            { "e9","C#" },
            { "e10","D" },
            { "e11","D#" },
            { "e12","E" },
        };
    }
}
